### ISSUE TITLE
HLK-SW16 is the opposite of the module state

### ISSUE THREAD

**Issue by Trace-star** [jameshilliard/hlk-sw16#1]
When I use HLK-SW16, I get the switch state is the opposite of the module state, how to solve

**Comment by jameshilliard** [comment]
What do you mean by opposite? Note that the blue lights on the switch when on indicate the circuit is open and when off circuit is closed.

You can see examples for how to use this library here:
https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/hlk_sw16.py
https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/switch/hlk_sw16.py

**Comment by jameshilliard** [comment]
Fixed in 4f0c5a7b76b42167f4dc9d2aa6312c7518a8cd56.
